### ISSUE TITLE
Make separate `hugr-passes` crate, depending on `hugr`

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/hugr#1000]
Already there are some passes implemented in the `hugr` crate that should be moved out, such as `constant_fold_pass` and `transform_all_cfgs`, and more are in the pipeline: #978 #945 #818 #561 . These should be moved into a separate crate, to avoid bloating the `hugr` crate and ensure that we have an API suitable for users to write their own passes.

**Comment by aborgna-q** [comment]
This may require adding a `hugr-internal` (or `hugr-core`) crate too, that exposes `HugrView` and related traits. See #294

**Comment by acl-cqc** [comment]
The only *real* issue here is that we need to make HugrMut `pub`. Is that objectionable?

**Comment by cqc-alec** [comment]
> The only _real_ issue here is that we need to make HugrMut `pub`. Is that objectionable?

`HugrMut` is already `pub`. (Not sure how long that has been the case.) So I don't think there are any blockers?
