### ISSUE TITLE
floats do not perfectly round trip serialize.

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1049]
To observe this uncomment the generator in  `impl Arbitrary for OpaqueValue`(currently in review in #999).

floating point types are hard. It is perhaps acceptable to not perfectly round trip. We should ensure that the following special values do round trip:
* NAN
* -INF
* +INF
* 0.0
* -0.0

For other values, perhaps a small error is Ok. Needs investigation and justification.

**Comment by cqc-alec** [comment]
Seems to be caused by https://github.com/serde-rs/json/issues/202 . (NAN, INF and -INF all serialize to "null".) We may need a custom serializer for `Float64` values to work around this.

**Comment by cqc-alec** [comment]
Or perhaps we can just forbid these values from `ConstF64`.
