### ISSUE TITLE
ci: Consider running a job that does `cargo test --release`

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1065]
This can find unsafe code that is accidentally working in `dev` profile.

It may well be that miri is sufficient for this.

**Comment by aborgna-q** [comment]
I'd say that inconsistencies between debug and release on safe code would not be hugr bugs, and it's not something we should spend CI time on.

For any unsafe code, that's what the `miri` tests are for. (We run them even though there is no `unsafe` currently in the crates).

Closing as WONTFIX.
