### ISSUE TITLE
`__version__` in `hugr-py/src/hugr/__init__.py` was not updated for version 0.2.1

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1083]
I see `https://github.com/python-poetry/poetry/issues/1652`, I think we should do this?

**Comment by aborgna-q** [comment]
It's annoying that `release-please` didn't update that value at all (not even to an incorrect version).
https://github.com/CQCL/hugr/pull/1040/commits/8034359bb578ea389c42c734b3a7fdda940e0fd0

Weirdly, the latest PR does include the change, so I'm not sure what changed (and if there's anything to fix in the automation)
https://github.com/CQCL/hugr/pull/1092/commits/a3c25624893b97daa535e2a84fb3ca851e923126

**Comment by aborgna-q** [comment]
👍 
For reference, the test was added in #1085 .
