### ISSUE TITLE
merge_bbs creating too many copies of self-loop edge

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#1143]
This relates to #1144 which reveals the bug (by making the Hugr fail validation), previously the multiple-edges had been going unnoticed.

The `merge_bbs.rs` test `in_loop` with `self_loop: true` replaces two BBs with one BB that has an edge back to itself. After performing the Replacement, the new BB in the Hugr has *four* edges back to itself (all from the same port).
I've checked the `Replacement` - the `replacement` Hugr contains exactly one self-edge, `mu_out` contains exactly one edge leaving the `replacement`, `mu_inp` is empty - all as expected.

The problem appears to arise immediately after this: https://github.com/CQCL/hugr/blob/1032b7a0cc7822371177e9877632580b1ed8daba/hugr-core/src/hugr/rewrite/replace.rs#L282

i.e. before we even inspect `mu_inp` / `mu_out` etc. So I believe this is due to https://github.com/CQCL/portgraph/issues/130 but I'm not clear why we see *four* copies of the edge as from that portgraph issue I would expect to see two.

**Comment by aborgna-q** [comment]
The next portgraph release should fix that. See https://github.com/CQCL/portgraph/pull/132
