### ISSUE TITLE
Add compression/decompression to serialisation

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1307]
When we start to add DebugInfo to Hugrs we will see an explosion in the size of serialised JSON. 

Add a binary format which is compressed JSON, with some small header identifying it. Suggest https://docs.rs/zstd/latest/zstd/ and/or https://crates.io/crates/flate2

**Comment by aborgna-q** [comment]
It may be useful to export a `load_hugr` helper that automatically detects the file format (with https://crates.io/crates/infer), and decompresses/deserialises it as needed.
