### ISSUE TITLE
Configuration/warnings for Opaque ops and types (not unconfigurable errors)

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#1335]
- [ ] `resolve_extension_ops` to raise some kind of warning when it can't find an extension. Perhaps `eprintln!` (worst) or crate `log` (better), or pass in an `&mut Vec<Warning>` and let the caller decide what to do. (Hugr CLI should log out, though could have suppression flags.)
- [ ] `resolve_extension_ops` is "all or nothing" for an extension, which is kind of good, but for an extension with binary `compute_signature`s (that you don't have), you must either
   * treat the entire extension as unknown, i.e. no checking of any non-binary-`compute_signature` ops that you *do* know about
   * provide an incomplete extension (without proper info on those OpDefs), thus returning an `Err` (not warning) if those ops are used
...maybe we need some way to flag ops as known-to-exist-but-unknown, or for `compute_signature` to signal that it can't compute the signature but this is not necessarily an error
- [ ] Consider moving some/all of this into validation (i.e. if it finds an OpaqueOp that was not resolved), or elsewhere (good to be able to gather all warnings without requiring rest of Hugr to be valid but implementation might be too complex and we might need some guarantee of validity to be able to issue warnings accurately)
- [ ] Add similar functionality for opaque types

**Comment by ss2165** [comment]
Outdated, closing in favour of #1432

**Comment by ss2165** [comment]
Outdated, closing in favour of https://github.com/CQCL/hugr/issues/1432
