### ISSUE TITLE
All ops and types need to belong to a loaded extension declaration.

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#1344]
This is a tracking issue for the goal that a valid HUGR must only contain ops and types that point to loaded extension declarations.

The current system allows opaque ops (not types) that point to extensions that may not be loaded (their cached signature is used for validation). This is a bit of a nasty backdoor that we probably don't need and should close. This follows from the closing of opaque type argument back doors: #1328.

In the new workflow, validation would always go to the extension pointed to to get the signature. If the signature is cached, it would check the cache matches what the extension reports, this could be turned off in validation config for speed (just accept the cached). The exception is ops that declare "I need a binary function to compute my signature" in which case validation would accept the cached if the binary is not available.

To make this possible but maintain the convenience of defining new ops/types on the fly (e.g. from guppy or tket2), we should add the notion of a hugr "package". This can hold multiple hugrs, and multiple extensions, serialised. The hugrs can point to said extensions, or to extensions that will be loaded separately. The cli tool for example can merge these extensions with whatever it loads before validation. Serialised extensions should be versioned. If extension and version match, the validation tool should ignore the packaged extension (with a warning) and just use the loaded one.

Hugr-py should make it easy to define extensions and package them with hugrs. 

Tasks: 

- [x] #1357
- [x] #1361
- [x] #1360
- [x] #1228 
- [x] #1358
- [x] #1359
- [x] #1374
- [x] #1412
- [x] #1362

Follow ups
#1363
Allow optional field names for in/out rows in opdefs in serialised extensions.
#1432 CLI warnings to say extensions expecting custom binary will be ignored (and cache used). Related to #1335.

**Comment by acl-cqc** [comment]
This may also relate to #1335 although that may possibly fit into #1363 ?
