### ISSUE TITLE
Include and load serialized std extensions in hugr-py

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/hugr#1450]
Currently we store the rust-defined std extensions as json files in `specification/std_extensions/`. There can be loaded by the extension model defined in hugr-py's `.serialization.extension`, but are not included in the wheels.

Instead, we define some operations separately on `.std`.
We should include the json files in the wheels (compressed with zstd?) and load them when exposing the std extensions from python. We'll still need definitions for operations that require binary-computed signatures (array ops), but we should be able to keep the rest synchronized between python and rust.

**Comment by ss2165** [comment]
The extensions should be small enough to avoid compression
