### ISSUE TITLE
Add `Option`-like type?

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/hugr#1473]
It would be useful to export a standard `Option`/`Optional` type definition from the prelude that can be used by fallible operations. (And include a const value definition).

This can currently be defined as a sum `[T] + []`, but having it as a common definition would ensure we have an homogeneous interface.

**Comment by ss2165** [comment]
This sounds like having utilities for using sums?

**Comment by aborgna-q** [comment]
Yeah, it should probably be something like the definition for `BOOL_T`, which is just an alias for a sum.
