### ISSUE TITLE
Move Array ops to a dedicated extension

### ISSUE THREAD

**Issue by doug-q** [CQCL/hugr#1497]
I'm not sure we've got the new array ops naming quite right. The operation names (mostly) do not mention array  This would be fine if they were in an array extension, but in prelude we now have `prelude.get`, `prelude.set` . These are very general names for ops that only work on a specific type. I suggest creating an `array` , or `prelude.array` extension.

**Comment by aborgna-q** [comment]
Also, add a value declaration in the extension
