### ISSUE TITLE
Panic in HugrView::linked_inputs/linked_outputs

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#1584]
This testcase seems "reasonable" to me:
```
    #[test]
    fn unconnected_outputs() {
        use crate::builder::test::simple_dfg_hugr;
        let hugr = simple_dfg_hugr();
        let mut it = hugr.linked_inputs(hugr.root(), 0);
        assert_eq!(it.next(), None);
    }
```
(it is quite legal to have no inputs linked to a Copyable output)
However `linked_inputs` panics in this `unwrap`: (https://github.com/CQCL/hugr/blob/24125995fc624579924f3a629d09a3e8ce372563/hugr-core/src/hugr/views.rs#L615-L621)

The same problem occurs using`linked_outputs` where one could perhaps argue that there should always be some outputs, but either way, surely we should return an empty iterator rather than panic?

**Comment by acl-cqc** [comment]
I wonder if it's time to drop the associated types in HugrView and use RPTIT?

**Comment by aborgna-q** [comment]
The root node of the hugr is a special case that does not have any ports, `hugr.linked_inputs(hugr.root(), 0)` is asking for an invalid port.

I see a couple options here:
- Leave things as-is
- Make `linked_outputs` return an empty iterator for invalid ports`
- Add unconnected ports to the hugr root. This will break validation.

**Comment by aborgna-q** [comment]
> I wonder if it's time to drop the associated types in HugrView and use RPTIT?

And yes, there's an old TODO to replace the `context_iterators` dependency. It's an annoying refactor, but should help clear up things.

**Comment by acl-cqc** [comment]
> * Add unconnected ports to the hugr root. This will break validation.

This seems a little odd to me - ATM the ports of the root node do not match its Signature. Seems reasonable not to have any ports at the portgraph level (there are no legal endpoints), but I'd have said they should exist at the Hugr level (as described by the Signature, so at least we could be consistent there). I think this is roughly your second option, *although* I think it'd be fair to panic (rather than return empty) for a port *not* described by the node's Signature (e.g. `linked_outputs(hugr.root(), 10)` in my example above)

**Comment by acl-cqc** [comment]
Thanks for the fix @aborgna-q ! :)
