### ISSUE TITLE
Allow custom ops with static constant input edges

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#1594]
### Discussed in https://github.com/CQCL/hugr/discussions/1342

<div type='discussions-op-text'>

<sup>Originally posted by **ss2165** July 24, 2024</sup>
This follows discussions mainly in #1308 

A constant static input to an op would would be some semantically significant data, that cannot be lost like metadata. This could be thought of as "literal properties" or "intrinsic parameters". 

If further we can elevate values to constants at compile time (constexpr evaluation) we can do powerful things with ops that need some structured, complicated, compile-time known data.

An open question is whether this data is available to binary compute_signature functions.</div>

**Comment by acl-cqc** [comment]
> Rename `LoadFunction` to `TypeApply`. Currently `LoadFunction` has a single output `Value` edge. Change this to a `Const` edge.

So `LoadFunction` is now static-function to static-const. This can wire into a `LoadConstant` if you want a `Value` e.g. if the successor of your LoadFunction was an `IndirectCall`.  Neat.

`Call` still takes Function and does type-apply itself? Or, how about we continue the same line and make `Call` take a `Value` input so could be applied only to (1) a `Const` or (2) a `TypeApply` of a `FuncDefn`?

**Comment by acl-cqc** [comment]
Yes, `Call` takes `Const` not `Function`, sorry!

**Comment by ss2165** [comment]
> With the feature as described it is not allowed for extension operations to take Function edges from FuncDefn/FuncDecl

This is the case in the PR linked above. I like the change you propose but I think that is a follow up feature so should be in a new issue.

**Comment by ss2165** [comment]
Moved to hugr "v2" model work #1433
