### ISSUE TITLE
Python ArrayValue reports wrong constant name

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#1821]
Is "ArrayValue" but should be "array" to match rust definition

**Comment by ss2165** [comment]
Unrelated to bug

**Comment by aborgna-q** [comment]
To add more info:
On the rust side we use `typetag` to resolve custom const to concrete implementations when deserializing.
The class name we resolve to is encoded in the `c` field of the json, and it corresponds (unless overwritten) to the rust class name.

In the array case, we use `ArrayVal` on both sides so it's correct.
We _could_ and maybe should rename these to `collections.array.const` or something similar, but for the moment it should be working correctly.
