### ISSUE TITLE
Tracking issue for HUGR polymorphism

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#416]
See discussion #285 

- [x] #396 
- [x] #405 
- [x] #374 
- [x] #419
- [x] #439
- [x] evaluate extension of previous to polymorphic function types not just type schemes
    - [x] if yes, then allow polymorphic Hugrs (declaring their bound type parameters) #657 
- [x] #658 
- [x] #787 
- [x] #904

**Comment by acl-cqc** [comment]
There is #1094 as a tidyup after #787 but I agree this is not really about polymorphism anymore ;)
