### ISSUE TITLE
Validation for graphs with resource variables

### ISSUE THREAD

**Issue by croyzor** [CQCL/hugr#457]
Currently, extension validation assumes that hugrs should be extensions-closed. Which is to say that every node in the hugr should have concrete extensions for its incoming and outgoing edges. This makes sense for a static function definition, but may be needlessly restrictive for other types of hugrs.

Concretely, in the below diagram, input0 could have an open extension variable as its input extensions. Extension inference could conclude that the rest of the graph makes sense given any value for this variable, but validation would complain that `DFG0`'s input doesn't have a concrete extension set!
```mermaid
flowchart
    direction TB
    subgraph DFG0
        direction TB
        subgraph DFG1
            direction TB
            Input1 --> op0
            op0 --> op1
            op1 --> Output1
        end
        Input0 --> DFG1
        Input1 --> DFG1
        DFG1 --> Output0
    end
```
The workaround for this lack of more permissive extension validation as introduced by #456 is for extension inference to return a _closure_ -- a mapping of solutions for extension sets in the graph which depend on open variables which it then passes to validation, allowing validation to operate on an extension-closed hugr.

I.e. extension inference checks that there is a solution given any value for the remaining extension variables, and for validation it sets their values to the empty extension set.

**Comment by acl-cqc** [comment]
Update: following #713 the main thing missing - given that we already [validate type-variables](https://github.com/CQCL/hugr/blob/d98fb791a5ca5651fba659e0e55da59db451a975/hugr/src/hugr/validate.rs#L525-L565) (including ExtensionSet ones) appearing in TypeArgs are declared - and that [all port kinds are valid similarly](https://github.com/CQCL/hugr/blob/d98fb791a5ca5651fba659e0e55da59db451a975/hugr/src/hugr/validate.rs#L265-L278) - we think the only things remaining are:
* the first `match` might want to include other LeafOps that can include Types (e.g. Noop). However, given #816, this may be unnecessary
* as well as validating the port-kinds of each node's signature, we should also validate the extension-delta

**Comment by acl-cqc** [comment]
New approach using extension typevars should let us do something similar to this following #709
