### ISSUE TITLE
Allow Extensions to provide binary code to validate values

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#483]
Values of opaque types can be used as type arguments, represented as `serde_yaml::Value`s - see [CustomTypeArg](https://github.com/CQCL-DEV/hugr/blob/1b836401f5d7ccd39d477fa50168a00a0a4c9e90/src/types/type_param.rs#L105).

Whereas the `CustomConst` trait used for constants allows construction-time checking in building instances of the custom struct implementing CustomConst, there's no mechanism for checking CustomTypeArgs.

A method `TypeDef::validate_value(&[TypeArg], serde_yaml::Value)` would do the trick, and then we need some way for extension providers to provide implementations (i.e. custom binary code - or possibly some kind of yaml schema).

**Comment by ss2165** [comment]
`CustomTypeArg` removed in #1328
