### ISSUE TITLE
Merge basic blocks

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#561]
i.e. when there is an edge from a BB with only one successor, to a BB with only one predecessor, the two can be combined. As a first step this would produce one BB containing two DFG nodes one of which consumes all outputs of the other, but then 2*InlineDFG operations to flatten them should remove false dependencies and enable additional optimizations.

Might require implementing both Replacement and/or InlineDFG rewrites...

**Comment by cqc-alec** [comment]
@acl-cqc We discussed this morning where this sort of thing (also #818 ) should go, and the general agreement that there should be a "hugr-passes" crate, in the hugr repo, where passes that operate on general HUGRs go. (Other quantum-specific passes would go in the TKET2 repo.) This makes for a cleaner separation between passes (which shouldn't rely on hugr internals) and core hugr. Does this seem reasonable?
