### ISSUE TITLE
Add function to validate a TypeParam

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#624]
The significant check is probably only at the leaves, specifically `TypeParam::Opaque`s, but we should check somewhere that we don't have an Opaque with a malformed CustomType like `List<5>` or similar (i.e., should be `List<SomeType>`)

**Comment by ss2165** [comment]
Can we close this as of #1328?

**Comment by acl-cqc** [comment]
Yes good spot! I don't see anything in any of the other "leaves" or elsewhere to validate.
