### ISSUE TITLE
Rename FunctionType::new_linear to new_endo

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#664]
Linearity is a property of a value, not a function on that value. So, possibilities?
* `new_symmetric`? (thanks to @seyon)
* `self_composable`? But would have to be `new_self_composable`, too long.
* Mathematically speaking, such functions are iterable - one can compute f^2, f^3 ... f^n. So `new_iterable`? But in a Rusty world, that sounds confusing
* `new_elidable`? as in, we could just wire the inputs through to the outputs
* `new_identity_type`? (It has the same type as the identity function, and/or, the signature is what you get by applying the identity function to the input *types*)

**Comment by cqc-alec** [comment]
I suggest `new_endomorphic` or `new_endo` for short ( https://en.wikipedia.org/wiki/Endomorphism ).

**Comment by ss2165** [comment]
`FunctionType::new_endofunction`?

**Comment by cqc-alec** [comment]
heh, almost snap

**Comment by acl-cqc** [comment]
Yes I was thinking there was something from category theory and Endofunction/morphism is exactly it. I like `new_endo` (adding function on the end seems a bit redundant)...
