### ISSUE TITLE
bug: Two call nodes for the same function must have matching resources

### ISSUE THREAD

**Issue by croyzor** [CQCL/hugr#695]
Because of the way FuncDefns are handled in extension inference, they have extension sets which will try to be matched with the extensions at their call sites. Meaning that if there are two `call`s of the same function, the `FuncDefn`'s extensions will be solved to match one of the `call` nodes, and the other will probably throw an error.

The branch `call-bug` [adds a test case](https://github.com/CQCL/hugr/commit/3f84c203ba0adc43cea1fb410b25ce102d4a1ce9) demonstrating the erroneous behaviour.

**Comment by acl-cqc** [comment]
So I think one possible/suggested solution was to split EdgeKind::Static into EdgeKind::Function (ignored during inference) and EdgeKind::Const (generating Equals constraints), not sure how easy/workable that is tho

**Comment by acl-cqc** [comment]
Note that a very similar situation exists if I have a `Const` and two `LoadConstant`s - the two must have the same extensions. However - unlike the case with `Call` - in the `Const` case we can work around the problem by adding a `Lift` node *after* the LoadConstant (on the Value out-edge, not the Static in-edge).

**Comment by acl-cqc** [comment]
....but the best way to look at that may be - if we have a *good* solution for `Call` then perhaps we can generalize to handle `LoadConstant` (which is a lot like a 0-args `Call`) the same way, potentially avoiding the need for Lift nodes after LoadConstant

**Comment by acl-cqc** [comment]
I believe this was fixed by #1142
