### ISSUE TITLE
Remove single source requirement for DSGs

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#743]
from @cqc-alec :

> The spec currently states that "In a data dependency subgraph, a valid ordering of operations can be achieved by topologically sorting the nodes starting from Input with respect to the Value and Order edges." I vote we drop this requirement, since it places unnecessary constraints on execution order (there's no reason why a LoadConstant operation shouldn't be executed before knowing the inputs to a DFG). If efficiency of topsort is a big concern we can find other ways to optimize it.

**Comment by cqc-alec** [comment]
I believe this was fixed in the spec by https://github.com/CQCL/hugr/pull/762 , but the implementation still needs updating (to not add the unnecessary Order edges).

**Comment by acl-cqc** [comment]
Do we actually have any implementation code adding such Order edges? I check e.g. https://github.com/CQCL/hugr/blob/968c8b03cb35478a05474d2e4f7d27f3c5f3adc5/src/builder/build_traits.rs#L73-L77 and https://github.com/CQCL/hugr/blob/968c8b03cb35478a05474d2e4f7d27f3c5f3adc5/src/builder/build_traits.rs#L352-L370 in the builder, and don't see anything; and we haven't implemented InsertConst(Ignore) rewrites...

**Comment by cqc-alec** [comment]
I may be wrong about that, but my assumption was based on comments @peter-campora made a few weeks ago where he was surprised by the presence of some Order edges.

**Comment by cqc-alec** [comment]
I can't find anywhere in the code where we do this either.

**Comment by cqc-alec** [comment]
OK! So can we close this issue?

**Comment by ss2165** [comment]
Looks like it, the validation code does not depend on it either https://github.com/CQCL/hugr/blob/0c910cf50ef5ef09065a47d39fff0d7d41f2b4c9/src/hugr/validate.rs#L376-L377
