### ISSUE TITLE
Allow TypeArg for a row of types

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#787]
TypeParam::List / TypeArg::List allows one to declare a list of types, and provide them as type args (also other kinds of list, not relevant here). But there's no way to use these outside a custom binary function. We should allow should a parameter to be used inside a tuple, sum, or function type (inputs or outputs), or anywhere a row is expected, so one can say e.g. `unpack_tuple` has a `TypeParam::List(TypeParam::Type)` and then inputs `Tuple(TypeArg::new_variable(0, TypeParam::List(TypeParam::Type))` and outputs that type variable.

**Comment by acl-cqc** [comment]
Discussion from #804:
[ @acl-cqc ]:
The value of the feature is to allow us to make operations like UnpackTuple, MakeTuple, etc., as library operations in the  prelude, rather than the current LeafOp enum of ops which (without this PR) cannot be expressed in the extension system...

[ @doug-q ]:
I disagree. There is only aesthetic value in making these ops library operations.

I instead understand the value to be to allow operations with variadic inputs/outputs to be defined. The cost of not allowing these to be defined is that one is forced, by their absence, to instead work with tuples. The requisite UnpackTuple operations introduce barriers to parallelism.

**Comment by acl-cqc** [comment]
> There is only aesthetic value in making these ops library operations.
> 
> I instead understand the value to be to allow operations with variadic inputs/outputs to be defined. The cost of not allowing these to be defined is that one is forced, by their absence, to instead work with tuples. The requisite UnpackTuple operations introduce barriers to parallelism.

So the concern here is, if MakeTuple etc. need to be "special" (defined in core Hugr) because they can't be defined in an extension - who says we've got all the other operations that also need to be special?

In particular, the core does not include such Tierkreis staples as `partial` and `eval`. One could imagine defining `eval` as taking a function with only a single argument type (perhaps but not necessarily a tuple), and a single value of that type. However, isn't one then going to need a "special" operation to turn a function of many ops into a function of just one? 

`partial` seems even harder in that current Tierkreis allows providing (or not) arguments in any order, so we might need operations to pull an arbitrary argument to the front of a row. (So partial is `(Function[A, B -> C], A -> Function[B -> C])` where all arguments other than the first have been tupled into the `B`.)

**However**, we *can* do arbitrary computation (using `List<Type>` params etc.) in *custom binary `compute_signature` functions*. This may let us do much or all of this, *but* on the condition that any all "row variables" have arity fixed at "compile time" (graph-definition time). I think pretty sure that this will rule out some higher-order graphs that we would be able to write otherwise (including in current Tierkreis), but maybe we need to exhibit some examples to see what we would be missing here.

**Comment by acl-cqc** [comment]
So perhaps, given I think we can do #816 without this, we should just put this issue "on hold" until we've figured out the basics of Tierkreis. (I guess #797 !)

**Comment by acl-cqc** [comment]
Yes, writing `compute_signature` (in place of the current e.g. https://github.com/CQCL/hugr/blob/18ac2777dee4513535131824fb1c76eda6651490/hugr/src/ops/leaf.rs#L79-L80) is what it'd take to move those out of the core and into the prelude, I think, and I think that is what #816 is.

**Comment by ss2165** [comment]
> However perhaps instead we translate from a high-level input format (that is not Hugr) to a lower-level Hugr format that is only internal to the runtime. (Indeed things like Tierkreis type inference might happen in this translation.)

I think this issue highlights a current tension in the design: HUGR is very machine friendly and hence can use fairly arcane expressions over the small-ish spec to express complicated things (e.g. the "compilation patterns" @doug-q refers to). However, Tierkreis is currently human writable and readable. If we instead say that guppy is going to take on the writing role, what about reading? For example, when viewing a tierkreis computation in progress in a nexus visualisation, does the compilation pattern for `eval` suffice...? (I think it would look very ugly)

My hope is that adding these higher order operations with `compute_signature` in an extension is enough to allow the "simple" expressivity in tierkreis read/write contexts, which can be "compiled away" using such patterns if we are compiling down away from tierkreis. Therefore I want to reinforce 
> but maybe we need to exhibit some examples to see what we would be missing here.

to see what this wouldn't cover.

**Comment by acl-cqc** [comment]
So let's think about having say an `eval` op, parameterized by two lists of types: `eval[*A,*B](Function[*A -> *B], *A) -> (*B)`. And then let's think about writing a Hugr for the "map" function (mapping a function over a list): `map[A,B](Function[A -> B], List[A]) -> (List[B])`.

Without #787, `eval` has to compute its type by binary `compute_signature`. The restriction that TypeArgs given to binary `compute_signature` *cannot include type variables* bites us here, as the graph for `map[A,B]` cannot have an op `eval[List(A), List(B)]` 👎 (i.e. passing two singleton lists of type).

However, what we can do is - anywhere we'd have a row of types - we statically pass *just the length* to `compute_signature`, which computes away and returns a type scheme polymorphic (via infallible substitution, rather than binary computation) over that many types. So `eval` has two `usize` params, and `eval[2,3]` returns `forall A,B,C,D,E. (Function(A,B -> C,D,E), A, B) -> (C, D, E)`. Now `map[A,B]` can have an op that's `eval[1,1,A,B]` (the first two TypeArgs are given to the binary `compute_signature` as per defn of eval, the remaining TypeArgs are fed into substitution).

I think this "trick" gets us a reasonable distance, and applies to #816 also. Obviously all arities must be fixed statically, and this'll be the main restriction on what we can express. (Never mind that this is not the easiest interface!)
