### ISSUE TITLE
Move `Noop, MakeTuple, UnpackTuple, Tag` to prelude extension

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#816]
Requires #787

**Comment by acl-cqc** [comment]
I think this can be done without #787 by defining custom binary `compute_signature` functions. This just moves code around (i.e. the code that currently compute signature of these ops gets moved into an extension), with I suspect a substantial increase in boilerplate. OTOH it makes the API more uniform.

As a side benefit it also brings fields such as
https://github.com/CQCL/hugr/blob/0bab47890065010583dd8f7a9857431cbf8adeeb/hugr/src/ops/leaf.rs#L18 and https://github.com/CQCL/hugr/blob/0bab47890065010583dd8f7a9857431cbf8adeeb/hugr/src/ops/leaf.rs#L32 into scope for this check: https://github.com/CQCL/hugr/blob/0bab47890065010583dd8f7a9857431cbf8adeeb/hugr/src/hugr/validate.rs#L544-L549 ....which "feels right", but (for these ops) doesn't catch anything that we wouldn't anyway in https://github.com/CQCL/hugr/blob/0bab47890065010583dd8f7a9857431cbf8adeeb/hugr/src/hugr/validate.rs#L222-L223 .

**Comment by acl-cqc** [comment]
We've done #787, so we can do this now without any "custom binary" code for `compute_signature`. I think we should.

Lift similarly (although Lift has limited lifespan, should disappear following #919)

CallIndirect similarly (this should go in the Tierkreis extension, not prelude).
