### ISSUE TITLE
Replace tuples with unary variants over type rows

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/hugr#864]
Following on from #860 and #861 .

**Comment by cqc-alec** [comment]
Just a thought about this: would it mean that tuples-of-tuples lose their structure, so that e.g. `((A,B),(C,D,E))` is indistinguishable from `((A,B,C),(D,E))`? Would this matter?

**Comment by ss2165** [comment]
Using `[]` to denote rows, I believe the change would be:
`((A,B),(C,D,E))` -> `Sum([Sum([A, B],), Sum([C, D, E])],)`
`((A,B, C),(D,E))` -> `Sum([Sum([A, B, C],), Sum([D, E])],)`

So there should be no loss of structure.

**Comment by cqc-alec** [comment]
> Using `[]` to denote rows, I believe the change would be: `((A,B),(C,D,E))` -> `Sum([Sum([A, B],), Sum([C, D, E])],)` `((A,B, C),(D,E))` -> `Sum([Sum([A, B, C],), Sum([D, E])],)`
> 
> So there should be no loss of structure.

Yup true.
