### ISSUE TITLE
Get rid of `Value`

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/hugr#874]
`Const`s are defined as `Values` plus a concrete type.

The difference between both types is confusing, specially at the API level.
In practice, most of the times that `Value` is used we do already know their `Type`.

This issue proposes either making `Value` private, or merging it directly with `Const`.

**Comment by ss2165** [comment]
@acl-cqc  says:
> Merging Const and Value seems like a good plan to me - store the Type only to the enum-variants of Value that don’t have it already, which I think might be just Sum (Tuple can figure out from contents, Function from the Hugr inside, Extension all CustomConsts can report their type), and add a method that returns the type (by match self)
