### ISSUE TITLE
JSON deserialization seems to be failing with `Syntax("invalid type: integer `123`, expected internally tagged enum Versioned")`

### ISSUE THREAD

**Issue by qartik** [CQCL/hugr#900]
We have a simple program in guppy which is serialized to JSON, but during deserialization we see this error:
```
Syntax("invalid type: integer `123`, expected internally tagged enum Versioned")
```

Here's the input JSON: [ms1.json](https://github.com/CQCL/hugr/files/14761709/ms1.json)

**Comment by aborgna-q** [comment]
guppy is using [`hugr 0.1.0`](https://github.com/CQCL/guppylang/blob/73e29f25ec90b8dfcc6517b961d6d1d13f694cb6/validator/Cargo.toml#L13C1-L13C26)'s serialisation schema. This is not compatible with the current definition.

We are aiming to update guppy with the release of hugr 0.3.0.

The error message should have told you about the version mismatch, I'll have to fix that.

**Comment by aborgna-q** [comment]
What version of `quantinuum-hugr` are you using?

With `HEAD` you'll get an error message saying:
```
Version 0 HUGR serialization format is not supported.
```

**Comment by qartik** [comment]
> What version of `quantinuum-hugr` are you using?

Currently on `quantinuum-hugr = "0.2.0"`, I believe I saw the error after downgrading to the released version `0.1.0` as well.

**Comment by qartik** [comment]
@aborgna-q if there is a working commit of `quantinuum-hugr` with existing guppy serialization, I'd like to use it temporarily as a workaround.

**Comment by aborgna-q** [comment]
With `quantinuum-hugr = "0.1.0"` ,

```rust
pub fn main() -> Result<(), Box<dyn std::error::Error>> {
    let file = std::fs::File::open("ms1.json")?;
    let reader = std::io::BufReader::new(file);
    let hugr: Result<hugr::Hugr, _> = serde_json::from_reader(reader);

    assert!(hugr.is_ok());

    println!("👍");
    Ok(())
}
```
runs correctly on my end.

**Comment by aborgna-q** [comment]
`quantinuum-hugr 0.2.0` also works with the same code

**Comment by qartik** [comment]
Thanks for confirming it was working at your end. I don't know the root cause still but I reorganized the way we were accepting the serialized input and the problem disappeared while simplifying the input interface. Closing.
