### ISSUE TITLE
No polymorphic closures

### ISSUE THREAD

**Issue by acl-cqc** [CQCL/hugr#904]
* Only FuncDefn (and FuncDecl) may declare binders
* `Type` hierarchy includes monomorphic function types only, not polymorphic ones.
* Two distinct `EdgeKind`s: one for values/closures (from Consts to their uses, including CallIndirect), i.e. no polymorphism; and one for functions (carries a polymorphic function type from a FuncDecl/Defn to a Call, only).
* Thus, no `TypeApply`, but `Call` does type application, as per #901
* Should simplify substitution logic as we no longer need to substitute polymorphic types in place of type variables, and don't need to substitute under binders (binders are only at the outermost level - function or opdef)

**Comment by croyzor** [comment]
The spec says that a `FuncDefn` is the child of a dataflow container, meaning that they can be nested. Should this be updated to say that `FuncDefn` can only be the child of a `Module`?

**Comment by acl-cqc** [comment]
> The spec says that a `FuncDefn` is the child of a dataflow container, meaning that they can be nested. Should this be updated to say that `FuncDefn` can only be the child of a `Module`?

No - but nesting is purely for namespacing/scoping (a "local" funcdefn can only have nonlocal edges to things within the same parent). A local funcdefn already cannot refer to any enclosing TypeParams, this is checked in validation.
