### ISSUE TITLE
(Maybe?) Extension Inference: infer one layer at a time

### ISSUE THREAD

**Issue by croyzor** [CQCL/hugr#918]
Post #904, all type arguments/variables refer only to the nearest FuncDefn that contains them.

In the presence of FuncDefns which can take ExtensionSet arguments, we need to be smarter about traversing the hugr when running extension inference. For instance, an extension identifier meaning "de Bruijn index 0" has different meanings depending on the `FuncDefn` it is contained within.

Hence, we should run inference on each hierarchy level of the graph, feeding results forward as appropriate.

Update: MAYBE we need this for #919, but possibly we can just be smarter with generating constraints. We *might* need it for #640, though (or might not!).

**Comment by acl-cqc** [comment]
I was gonna say, obsolete since #1142 - but could also say, done by that PR, in that #1142 infers hierarchically (children before parent) anyway....
