### ISSUE TITLE
chore: Require BREAKING CHANGES footer on breaking PRs

### ISSUE THREAD

**Issue by ss2165** [CQCL/hugr#980]
Ideally enforce breaking PRs have a `BREAKING_CHANGES: ...` comment populated in the description

**Comment by aborgna-q** [comment]
The `BREAKING_CHANGES` enforcement should rather be done in CI. We could extend `pr-title.yml` and add instructions to the help message.

Annoyingly the `amannn/action-semantic-pull-request` action we use there does not actually interpret the title, so if we want to check whether the pr is breaking we have to do a manual regex:

https://github.com/CQCL/hugr/blob/597a866823b637928d1d4e99fd2b5da7cadb0e1d/.github/workflows/pr-title.yml#L87-L93
