### ISSUE TITLE
Const-folding of logical operations fails

### ISSUE THREAD

**Issue by cqc-alec** [CQCL/hugr#990]
Logical operations are not being const-folded when they should be.

I think the problem is with [this function](https://github.com/CQCL/hugr/blob/14c48afc8ab5b724d83ff8eb22d846df7d7ec6f6/hugr/src/std_extensions/logic.rs#L193), which compares values that look like
```
Extension { e: ExtensionValue(ConstBool { value: true }) }
```
(the output of `sorted_consts()`)
with values that look like
```
Sum { tag: 1, values: [], sum_type: Unit { size: 2 } }
```
(the value of `true_val`).

Since these are unequal, `read_inputs` returns `None`.

**Comment by ss2165** [comment]
what is a `ConstBool`? Why is it being used rather than the 2-ary UnitSum?

**Comment by cqc-alec** [comment]
Ah, because I'm an idiot. I had introduced this in a previous commit on my branch, and then forgotten!

I will close this.
